// AUTO-GENERATED by scripts/generate-menu-registry.mjs — do not edit by hand.
// Add a file under src/modules/menu/items/{category}/ and run `pnpm menu:registry`.
import type { MenuItem } from '../MenuItem.js';
import item0 from './character/profile.js';
import item1 from './combat/boss.js';
import item2 from './combat/continue.js';
import item3 from './combat/fight.js';
import item4 from './combat/first.js';
import item5 from './combat/gate.js';
import item6 from './combat/hunt.js';
import item7 from './combat/last.js';
import item8 from './combat/next.js';
import item9 from './combat/prev.js';
import item10 from './combat/result.js';
import item11 from './confirmation/cancel.js';
import item12 from './confirmation/confirm.js';
import item13 from './daily/claim.js';
import item14 from './daily/daily.js';
import item15 from './daily/quests.js';
import item16 from './daily/reroll.js';
import item17 from './navigation/back.js';
import item18 from './navigation/close.js';
import item19 from './navigation/home.js';
import item20 from './navigation/refresh.js';
import item21 from './system/help.js';

export const MENU_ITEMS: readonly MenuItem[] = [
	{ ...item0, name: 'profile', category: 'character' },
	{ ...item1, name: 'boss', category: 'combat' },
	{ ...item2, name: 'continue', category: 'combat' },
	{ ...item3, name: 'fight', category: 'combat' },
	{ ...item4, name: 'first', category: 'combat' },
	{ ...item5, name: 'gate', category: 'combat' },
	{ ...item6, name: 'hunt', category: 'combat' },
	{ ...item7, name: 'last', category: 'combat' },
	{ ...item8, name: 'next', category: 'combat' },
	{ ...item9, name: 'prev', category: 'combat' },
	{ ...item10, name: 'result', category: 'combat' },
	{ ...item11, name: 'cancel', category: 'confirmation' },
	{ ...item12, name: 'confirm', category: 'confirmation' },
	{ ...item13, name: 'claim', category: 'daily' },
	{ ...item14, name: 'daily', category: 'daily' },
	{ ...item15, name: 'quests', category: 'daily' },
	{ ...item16, name: 'reroll', category: 'daily' },
	{ ...item17, name: 'back', category: 'navigation' },
	{ ...item18, name: 'close', category: 'navigation' },
	{ ...item19, name: 'home', category: 'navigation' },
	{ ...item20, name: 'refresh', category: 'navigation' },
	{ ...item21, name: 'help', category: 'system' },
];
