/** Catalog display text. Keep entry keys stable; run db:seed after editing. */
export const WEAPONS_TEXT = {
	'1': {
		name: "Initiate's Blade",
		mythology: 'Neutral',
		passiveName: 'No Passive',
		passiveDescription: 'A plain training blade issued to every new adventurer.',
		lore: 'Standard-issue steel. It has ended more arguments than wars.',
	},
	'101': {
		name: 'Kampilan of the Rajah',
		mythology: 'Filipino',
		passiveName: 'Warlord’s Edge',
		passiveDescription: '+5% damage against enemies with higher max HP than you.',
		lore: 'The long sword of a rajah who never lost a duel on his own shore.',
	},
	'102': {
		name: 'Hunter’s Sinew Bow',
		mythology: 'Filipino',
		passiveName: 'First Blood',
		passiveDescription: 'The first hit of each battle deals +10% damage.',
		lore: 'Strung with the sinew of a beast that only ever missed once.',
	},
	'201': {
		name: 'Spear of Agila',
		mythology: 'Filipino',
		passiveName: 'Sky Dive',
		passiveDescription: 'Grants +8% crit chance when attacking from full HP.',
		lore: 'Forged from a feather of the great eagle-god and a fallen star.',
	},
	'301': {
		name: 'Kris of the Eclipse',
		mythology: 'Filipino',
		passiveName: 'Eclipse Mark',
		passiveDescription: 'Crits apply a mark; marked targets take +15% damage for 2 rounds.',
		lore: 'Wavy-bladed and wavy-tempered: it drinks the light on the day of the eclipse.',
	},
	'401': {
		name: 'Kampilan of Kaptan',
		mythology: 'Filipino',
		passiveName: 'Sky Sunder',
		passiveDescription: 'The sky-lord\u2019s blade splits the firmament with every swing.',
		lore: 'Forged in the first lightning, wielded by the primordial lord of the sky.',
	},
	'103': {
		name: 'Spear of Agila',
		mythology: 'Filipino',
		passiveName: 'Eagle Dive',
		passiveDescription: 'Lao xuống như đại bàng bổ mồi.',
		lore: 'Giáo chiến của các võ sĩ thành cổ.',
	},
	'104': {
		name: 'Wasp Needle Daggers',
		mythology: 'Filipino',
		passiveName: 'Twin Sting',
		passiveDescription: 'Hai lưỡi như vòi ong bắp cày.',
		lore: 'Rút từ tổ ong thiêng trên dãy Sierra Madre.',
	},
	'202': {
		name: 'Mjolnir Shard Mace',
		mythology: 'Norse',
		passiveName: 'Storm Echo',
		passiveDescription: 'Mảnh sấm rắn còn vang vọng sét.',
		lore: 'Vụn vỡ từ một cây búa thần rơi xuống biển phương Bắc.',
	},
	'203': {
		name: 'Anubis Hook',
		mythology: 'Egyptian',
		passiveName: 'Soul Weigh',
		passiveDescription: 'Móc cân linh hồn, khoét vào điểm yếu.',
		lore: 'Rút từ móc cân phán quyết của các quan tài Ai Cập, mòn vẹt bởi ngàn hồn.',
	},
	'302': {
		name: 'Kusanagi Replica',
		mythology: 'Japanese',
		passiveName: 'Grass Cleaver',
		passiveDescription: 'Cả thảo nguyên cúi mình trước lưỡi.',
		lore: 'Bản sao rèn từ cọng cỏ thần trong đền cố.',
	},
	'303': {
		name: 'Gungnir Splinter',
		mythology: 'Norse',
		passiveName: 'Oath Pierce',
		passiveDescription: 'Mảnh giáo của lời thề không bao giờ trượt.',
		lore: 'Gỗ tần bì từ nhánh giáo Odin gãy trong Laufrey.',
	},
	'402': {
		name: 'Ra Sun Lance',
		mythology: 'Egyptian',
		passiveName: 'Solar Barque',
		passiveDescription: 'Cây giáo kéo mặt trời băng qua bầu trời.',
		lore: 'Khi Ra nghỉ ngơi, cây giáo này thay ngài giữ bầu trời.',
	},
};
