/** Catalog display text. Keep entry keys stable; run db:seed after editing. */
export const ARMORS_TEXT = {
	'1': {
		name: "Initiate's Garb",
		mythology: 'Neutral',
		passiveName: 'No Passive',
		passiveDescription: 'A simple woven tunic that has saved more recruits than any doctrine.',
		lore: 'Standard-issue cloth, smelling faintly of the barracks.',
	},
	'101': {
		name: 'Bakunawa Scale Mail',
		mythology: 'Filipino',
		passiveName: 'Serpent Hide',
		passiveDescription: 'Reduces crit damage taken by 10%.',
		lore: 'Plates cut from a shed scale of the moon-eater. Still cold to the touch.',
	},
	'102': {
		name: 'Diwata Silk Vest',
		mythology: 'Filipino',
		passiveName: 'Forest Blessing',
		passiveDescription: 'Regenerates 1% max HP per round while below half HP.',
		lore: 'Woven by diwata of the middle forest; it never stains and never rots.',
	},
	'201': {
		name: 'Aegis of Mayari',
		mythology: 'Filipino',
		passiveName: 'Moonward',
		passiveDescription: 'Once per battle, survives a killing blow with 1 HP.',
		lore: 'The silver half of the war-moon, hammered into a breastplate by the moon goddess herself.',
	},
	'401': {
		name: 'Mantle of the First Dawn',
		mythology: 'Filipino',
		passiveName: 'First Dawn',
		passiveDescription: 'Woven from the light that ended the first night.',
		lore: 'When Apolaki first rose, his rays left an imprint on the sky; this mantle is its echo.',
	},
	'103': {
		name: 'Manananggal Wing Half-Cloak',
		mythology: 'Filipino',
		passiveName: 'Severed Flight',
		passiveDescription: 'Đôi cánh cắt lìa vẫn đập trong gió.',
		lore: 'Vải dệt từ mảnh cánh của kẻ săn đêm.',
	},
	'104': {
		name: 'Bamboo Warden Cuirass',
		mythology: 'Filipino',
		passiveName: 'Grove Guard',
		passiveDescription: 'Tre già dày hơn thép',
		lore: 'Đan từ tre trăm tuổi của những kẻ canh rừng.',
	},
	'202': {
		name: 'Freki Wolf Harness',
		mythology: 'Norse',
		passiveName: 'Wolves Feast',
		passiveDescription: 'Da sói của Freki, ngấu nghiến mọi đòn.',
		lore: 'Da của sói chiến thần, giờ khoác lên vai người.',
	},
	'203': {
		name: 'Scarab Laminar',
		mythology: 'Egyptian',
		passiveName: 'Dawn Roll',
		passiveDescription: 'Lá chắn bọ hung lăn mặt trời mỗi bình minh.',
		lore: 'Vảy bọ hung gắn theo đúng trật tự vũ trụ.',
	},
	'302': {
		name: 'Susanoo Storm Robe',
		mythology: 'Japanese',
		passiveName: 'Tide Tempest',
		passiveDescription: 'Áo bào cuôn theo bão biển.',
		lore: 'Của thần bão sau khi bị trục xuất khỏi thiên giới.',
	},
	'402': {
		name: 'Aegis of Athena',
		mythology: 'Greek',
		passiveName: 'Gorgon Gaze',
		passiveDescription: 'Đầu Gorgon trên ngực khiếp kẻ nhìn.',
		lore: 'Khi Athena di chuyển, cả chiến trường nghe tiếng rắn rít.',
	},
};
