/** Catalog display text. Keep entry keys stable; run db:seed after editing. */
export const DEITIES_TEXT = {
	'1': {
		name: 'Bathala',
		mythology: 'Filipino',
		blessingName: 'Guardian Light',
		blessingDescription: 'Restores a small portion of HP at the end of each round.',
		lore: 'The supreme deity of the Filipino pantheon, keeper of the sky and protector of mortals.',
	},
	'2': {
		name: 'Amihan',
		mythology: 'Filipino',
		blessingName: 'Tailwind',
		blessingDescription: 'Increases the chance to act first each round.',
		lore: 'The bird-shaped deity of the northeast winds, bearer of calm and swiftness.',
	},
	'3': {
		name: 'Amanikable',
		mythology: 'Filipino',
		blessingName: 'Tidal Wrath',
		blessingDescription: 'Sea-born rage: outgoing damage rises as HP falls.',
		lore: 'The ill-tempered patron of fishermen, whose storms swallowed careless boats whole.',
	},
	'101': {
		name: 'Bakunawa',
		mythology: 'Filipino',
		blessingName: 'Moon Devourer',
		blessingDescription: 'Every few rounds, swallows the moon: a heavy bonus strike.',
		lore: 'The serpent-dragon that rises from the sea to swallow the moon, plunging the world into eclipse.',
	},
	'102': {
		name: 'Mayari',
		mythology: 'Filipino',
		blessingName: 'Lunar Veil',
		blessingDescription: 'Moonlight cloak reduces incoming damage for one round after being struck.',
		lore: 'The one-eyed goddess of the moon, who fought the war-god to a standstill for the right to rule the night.',
	},
	'103': {
		name: 'Apolaki',
		mythology: 'Filipino',
		blessingName: 'Solar Fury',
		blessingDescription: 'Blinding sunlight adds bonus damage on every attack.',
		lore: 'The god of the sun and patron of warriors, whose blazing eye never blinks in battle.',
	},
	'201': {
		name: 'Maria Makiling',
		mythology: 'Filipino',
		blessingName: 'Mountain Grace',
		blessingDescription: 'The mountain spirit shields her champion: large damage reduction below half HP.',
		lore: 'The diwata of Mount Makiling, beautiful and merciful to the pure, merciless to those who betray her.',
	},
	'301': {
		name: 'Kaptan',
		mythology: 'Filipino',
		blessingName: 'Sky Sovereign',
		blessingDescription: 'Once per battle, an act of divine providence nullifies all damage taken that round.',
		lore: 'The primordial lord of the sky, who planted the bamboo from which the first humans sprang.',
	},
	'4': {
		name: 'Freyja',
		mythology: 'Norse',
		blessingName: 'Seidr Mending',
		blessingDescription: 'Phép Seidr vá áo giáp, hồi một phần HP cuối mỗi hiệp.',
		lore: 'Nàng thủ lĩnh Vanir của tình yêu và chiến tranh, người dạy pháp thuật cho các vị thần.',
	},
	'5': {
		name: 'Artemis',
		mythology: 'Greek',
		blessingName: 'Hunter Wind',
		blessingDescription: 'Gió rừng theo bước thợ săn, tăng cơ hội ra đòn trước.',
		lore: 'Nàng thợ săn trăng bạc, không bao giờ bắn trước khi chắc chắn trúng.',
	},
	'6': {
		name: 'Bastet',
		mythology: 'Egyptian',
		blessingName: "Cat's Wrath",
		blessingDescription: 'Nữ thần mèo gầm lên, sát thương dâng cao khi máu cạn.',
		lore: 'Nữ thần sư tử bảo vệ gia đình, dịu dàng với người thân, hung tợn với kẻ thù.',
	},
	'7': {
		name: 'Tsukuyomi',
		mythology: 'Japanese',
		blessingName: 'Moon Silence',
		blessingDescription: 'Ánh trăng lạnh bao lấy thân, dập bớt đòn đánh sau khi trúng chiêu.',
		lore: 'Thần trăng đêm, hiện thân của trật tự và im lặng tuyệt đối.',
	},
	'104': {
		name: 'Loki',
		mythology: 'Norse',
		blessingName: 'Trickster Surge',
		blessingDescription: 'Lừa dối và cuồng nộ: càng yếu, đòn đánh càng điên loạn.',
		lore: 'Kẻ ngụy tạo của Asgard, miệng lưỡi sắc hơn bất kỳ lưỡi kiếm nào.',
	},
	'105': {
		name: 'Hermes',
		mythology: 'Greek',
		blessingName: 'Winged Sandals',
		blessingDescription: 'Sandal có cánh của sứ thần, luôn đến trước mọi đòn đánh.',
		lore: 'Sứ thần nhanh nhất Olympus, người đưa tin giữa hai thế giới.',
	},
	'106': {
		name: 'Anubis',
		mythology: 'Egyptian',
		blessingName: 'Embalmer Shroud',
		blessingDescription: 'Khăn liệm của người ướp xác che chắn, dập bớt đòn kế tiếp.',
		lore: 'Thần xác chết đầu chó, canh ngọ môn giữa hai thế giới.',
	},
	'107': {
		name: 'Susanoo',
		mythology: 'Japanese',
		blessingName: 'Storm Slash',
		blessingDescription: 'Thỉnh thoảng gọi cơn bão, chém một đòn nặng gấp đôi.',
		lore: 'Thần bão biển bị trục xuất, từng chém con rắn tám đầu Yamata.',
	},
	'202': {
		name: 'Thor',
		mythology: 'Norse',
		blessingName: 'Lightning Wrath',
		blessingDescription: 'Sét Mjolnir nạp vào từng đòn đánh của ngươi.',
		lore: 'Vệ thần của nhân loại, tiếng búa của ngươi là tiếng sấm.',
	},
	'203': {
		name: 'Athena',
		mythology: 'Greek',
		blessingName: 'Aegis Guard',
		blessingDescription: 'Hòn khiên Aegis che chắn khi ngươi yếu thế.',
		lore: 'Nữ thần trí tuệ và chiến tranh chính nghĩa, sinh ra từ đầu Zeus.',
	},
	'204': {
		name: 'Ra',
		mythology: 'Egyptian',
		blessingName: 'Sun Barque Fire',
		blessingDescription: 'Lửa từ thuyền mặt trời thiêu đốt từng nhát chém.',
		lore: 'Vua của các vị thần, mỗi đêm ngươi phải chiến đấu qua bóng tối để bình minh lên.',
	},
	'302': {
		name: 'Odin',
		mythology: 'Norse',
		blessingName: 'Allfather Providence',
		blessingDescription: 'Đôi mắt hy đổi lấy trí tuệ: một lần mỗi trận, thiên lệnh hoá giải trọn đòn.',
		lore: 'Chúa tể của tất cả, treo mình trên cây thế giới chín đêm để đọc được vận mệnh.',
	},
	'303': {
		name: 'Amaterasu',
		mythology: 'Japanese',
		blessingName: 'Eternal Dawn',
		blessingDescription: 'Bình minh vĩnh cửu thiêu trong từng đòn đánh.',
		lore: 'Nữ thần mặt trời, khi nàng trốn trong hang, cả thế giới chìm trong đêm.',
	},
};
