CREATE TABLE "active_battles" (
	"battle_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "active_battles_battle_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"message_id" text NOT NULL,
	"battle_type" text NOT NULL,
	"mob_id" integer NOT NULL,
	"enemy_level" integer,
	"player_hp" integer NOT NULL,
	"player_max_hp" integer NOT NULL,
	"enemy_hp" integer NOT NULL,
	"enemy_max_hp" integer NOT NULL,
	"current_turn" integer DEFAULT 1 NOT NULL,
	"player_goes_first" boolean NOT NULL,
	"active_debuffs" jsonb NOT NULL,
	"battle_log" jsonb NOT NULL,
	"overcharge_pct" integer DEFAULT 0 NOT NULL,
	"bleed_stacks" jsonb NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "active_battles_unique_0" UNIQUE("discord_id")
);
--> statement-breakpoint
CREATE TABLE "active_casino_sessions" (
	"session_id" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"game" text NOT NULL,
	"status" text NOT NULL,
	"bet_amount" integer NOT NULL,
	"balance_before" integer NOT NULL,
	"balance_after_debit" integer NOT NULL,
	"payout" integer,
	"balance_after" integer,
	"channel_id" text,
	"message_id" text,
	"state_json" jsonb NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "active_duel_participants" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"duel_id" text NOT NULL,
	"lock_token" text NOT NULL,
	"role" text NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "active_duels" (
	"duel_id" text PRIMARY KEY NOT NULL,
	"lock_token" text NOT NULL,
	"challenger_id" text NOT NULL,
	"opponent_id" text NOT NULL,
	"duel_type" text NOT NULL,
	"stake" integer,
	"status" text NOT NULL,
	"guild_id" text,
	"channel_id" text,
	"message_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"accepted_at" timestamp,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "active_ranked_fights" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"lock_token" text NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "armor_roster" (
	"armor_roster_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "armor_roster_armor_roster_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"tier" text NOT NULL,
	"mythology" text NOT NULL,
	"passive_key" text NOT NULL,
	"passive_name" text NOT NULL,
	"passive_description" text NOT NULL,
	"lore" text,
	"image_filename" text,
	"is_available" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auto_raids" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"ends_at" timestamp NOT NULL,
	"combat_level" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "boss_attack_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "boss_attack_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"boss_spawn_id" text NOT NULL,
	"guild_id" text NOT NULL,
	"discord_id" text NOT NULL,
	"mob_id" integer NOT NULL,
	"total_damage" integer DEFAULT 0 NOT NULL,
	"attacked_at" timestamp DEFAULT now() NOT NULL,
	"last_daily_reset" text NOT NULL,
	CONSTRAINT "boss_attack_log_unique_0" UNIQUE("boss_spawn_id","discord_id")
);
--> statement-breakpoint
CREATE TABLE "boss_spawn_queue" (
	"queue_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "boss_spawn_queue_queue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"guild_id" text NOT NULL,
	"boss_name" text NOT NULL,
	"requested_by" text NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"claim_started_at" timestamp,
	"spawned_at" timestamp,
	"cancelled_at" timestamp,
	"cancelled_by" text,
	"spawn_id" text
);
--> statement-breakpoint
CREATE TABLE "boss_state" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"spawn_id" text NOT NULL,
	"mob_id" integer NOT NULL,
	"boss_level" integer,
	"max_hp" integer NOT NULL,
	"current_hp" integer NOT NULL,
	"scaled_atk" integer NOT NULL,
	"scaled_def" integer NOT NULL,
	"spawn_at" timestamp NOT NULL,
	"expires_at" timestamp NOT NULL,
	"status" text NOT NULL,
	"spawn_source" text NOT NULL,
	"last_attack_at" timestamp,
	"passive_state" jsonb
);
--> statement-breakpoint
CREATE TABLE "casino_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "casino_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"game" text NOT NULL,
	"bet_amount" integer NOT NULL,
	"result" text NOT NULL,
	"payout" integer NOT NULL,
	"balance_before" integer NOT NULL,
	"balance_after" integer NOT NULL,
	"metadata" jsonb,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cosmetic_catalog" (
	"cosmetic_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cosmetic_catalog_cosmetic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cosmetic_key" text NOT NULL,
	"category" text NOT NULL,
	"tier" text NOT NULL,
	"display_name" text NOT NULL,
	"token_cost" integer DEFAULT 0 NOT NULL,
	"is_base" boolean DEFAULT false NOT NULL,
	"has_top_label" boolean DEFAULT false NOT NULL,
	"display_filename" text,
	"render_filename" text,
	"victory_filename" text,
	"defeated_filename" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"skin_code" text,
	CONSTRAINT "cosmetic_catalog_unique_0" UNIQUE("cosmetic_key")
);
--> statement-breakpoint
CREATE TABLE "daily_quest_completion_rewards" (
	"discord_id" text NOT NULL,
	"quest_date" text NOT NULL,
	"sacred_relics" integer DEFAULT 1 NOT NULL,
	"claimed_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "daily_quest_completion_rewards_discord_id_quest_date_pk" PRIMARY KEY("discord_id","quest_date")
);
--> statement-breakpoint
CREATE TABLE "daily_quests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_quests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"quest_type" text NOT NULL,
	"target_count" integer NOT NULL,
	"current_count" integer DEFAULT 0 NOT NULL,
	"reward_credux" integer NOT NULL,
	"reward_belief_shards" integer NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"quest_date" text NOT NULL,
	CONSTRAINT "daily_quests_unique_0" UNIQUE("discord_id","quest_type","quest_date")
);
--> statement-breakpoint
CREATE TABLE "deity_roster" (
	"deity_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deity_roster_deity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"mythology" text NOT NULL,
	"tier" text NOT NULL,
	"base_hp" integer NOT NULL,
	"base_atk" integer NOT NULL,
	"base_def" integer NOT NULL,
	"blessing_key" text NOT NULL,
	"blessing_name" text NOT NULL,
	"blessing_description" text NOT NULL,
	"lore" text,
	"image_filename" text,
	"is_available" boolean DEFAULT true NOT NULL,
	"blessing_scaling" text NOT NULL,
	CONSTRAINT "deity_roster_unique_0" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "dev_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dev_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dev_id" text NOT NULL,
	"action_type" text NOT NULL,
	"target_discord_id" text NOT NULL,
	"amount_or_detail" text,
	"pre_reset_snapshot" jsonb,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "equipped_skins" (
	"discord_id" text NOT NULL,
	"category" text NOT NULL,
	"cosmetic_id" integer,
	"override_path" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "equipped_skins_discord_id_category_pk" PRIMARY KEY("discord_id","category")
);
--> statement-breakpoint
CREATE TABLE "essence_bag_def" (
	"bag_key" text PRIMARY KEY NOT NULL,
	"open_command" text NOT NULL,
	"essence_tier" text NOT NULL,
	"essence_cost" integer NOT NULL,
	"credux_cost" integer NOT NULL,
	"rune_pool" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "essence_exchange_submissions" (
	"submission_id" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "game_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "game_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"action" text NOT NULL,
	"item_type" text,
	"previous_credux" integer,
	"updated_credux" integer,
	"previous_belief_shards" integer,
	"updated_belief_shards" integer,
	"previous_chest_count" integer,
	"updated_chest_count" integer,
	"previous_relic_count" integer,
	"updated_relic_count" integer,
	"previous_essence_count" integer,
	"updated_essence_count" integer,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mob_roster" (
	"mob_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mob_roster_mob_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"mythology" text NOT NULL,
	"mob_type" text NOT NULL,
	"base_hp" integer NOT NULL,
	"base_atk" integer NOT NULL,
	"base_def" integer NOT NULL,
	"base_crit" real NOT NULL,
	"hp_per_level" integer DEFAULT 0 NOT NULL,
	"atk_per_level" integer DEFAULT 0 NOT NULL,
	"def_per_level" integer DEFAULT 0 NOT NULL,
	"skill_key" text NOT NULL,
	"skill_name" text NOT NULL,
	"skill_description" text NOT NULL,
	"immunity_tags" jsonb NOT NULL,
	"special_flags" jsonb NOT NULL,
	CONSTRAINT "mob_roster_business_key" UNIQUE("name","mythology","mob_type")
);
--> statement-breakpoint
CREATE TABLE "pity_counters" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"pity_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pvp_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pvp_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"duel_id" text,
	"challenger_id" text NOT NULL,
	"opponent_id" text NOT NULL,
	"winner_id" text NOT NULL,
	"challenger_damage" integer NOT NULL,
	"opponent_damage" integer NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pvp_shop_purchases" (
	"discord_id" text NOT NULL,
	"season_id" integer NOT NULL,
	"item_key" text NOT NULL,
	"qty" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "pvp_shop_purchases_discord_id_season_id_item_key_pk" PRIMARY KEY("discord_id","season_id","item_key")
);
--> statement-breakpoint
CREATE TABLE "raid_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "raid_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"battle_type" text NOT NULL,
	"enemy_name" text NOT NULL,
	"enemy_tier" text NOT NULL,
	"result" text NOT NULL,
	"exp_earned" integer DEFAULT 0 NOT NULL,
	"updated_exp" integer NOT NULL,
	"belief_shards_dropped" integer DEFAULT 0 NOT NULL,
	"updated_belief_shards" integer NOT NULL,
	"credux_earned" integer DEFAULT 0 NOT NULL,
	"updated_credux" integer NOT NULL,
	"chest_dropped" text,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "raid_reward_daily_totals" (
	"discord_id" text NOT NULL,
	"reward_date" text NOT NULL,
	"silver_chests" integer DEFAULT 0 NOT NULL,
	"gold_chests" integer DEFAULT 0 NOT NULL,
	"belief_shards" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "raid_reward_daily_totals_discord_id_reward_date_pk" PRIMARY KEY("discord_id","reward_date")
);
--> statement-breakpoint
CREATE TABLE "raid_reward_grants" (
	"reward_key" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"reward" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ranked_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ranked_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"player_id" text NOT NULL,
	"opponent_id" text NOT NULL,
	"result" text NOT NULL,
	"rating_before" integer NOT NULL,
	"rating_after" integer NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ranked_reward" (
	"bracket" text PRIMARY KEY NOT NULL,
	"weekly_credux" integer DEFAULT 0 NOT NULL,
	"weekly_payload" jsonb NOT NULL,
	"season_end_payload" jsonb NOT NULL,
	"weekly_valor" integer DEFAULT 0 NOT NULL,
	"season_valor" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rune_roster" (
	"rune_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rune_roster_rune_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"lane" text NOT NULL,
	"effect_key" text NOT NULL,
	"tier" text NOT NULL,
	"value" real NOT NULL,
	"description" text NOT NULL,
	"is_available" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seasons" (
	"season_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seasons_season_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"theme" text,
	"starts_at" timestamp NOT NULL,
	"ends_at" timestamp NOT NULL,
	"featured_deity_id" integer,
	"is_active" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "server_config" (
	"guild_id" text PRIMARY KEY NOT NULL,
	"prefix" text NOT NULL,
	"announcement_channel_id" text,
	"boss_announcement_channel_id" text,
	"bot_channel_id" text,
	"configured_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "socket_unlock_cost" (
	"tier" text NOT NULL,
	"slot_index" integer NOT NULL,
	"essence_tier" text NOT NULL,
	"essence_cost" integer NOT NULL,
	"credux_cost" integer NOT NULL,
	CONSTRAINT "socket_unlock_cost_tier_slot_index_pk" PRIMARY KEY("tier","slot_index")
);
--> statement-breakpoint
CREATE TABLE "stripe_events" (
	"event_id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"processed_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "summon_reward_grants" (
	"reward_key" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"source" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supporter_grants" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supporter_grants_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"action" text NOT NULL,
	"tier" text,
	"months" integer,
	"paypal_ref" text,
	"granted_by" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supporter_item_grants" (
	"grant_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supporter_item_grants_grant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"item_key" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"grant_reason" text NOT NULL,
	"grant_ref" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "supporter_item_grants_unique_0" UNIQUE("discord_id","item_key","grant_reason","grant_ref")
);
--> statement-breakpoint
CREATE TABLE "supporter_token_ledger" (
	"entry_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supporter_token_ledger_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"delta" integer NOT NULL,
	"reason" text NOT NULL,
	"ref" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supporters" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"tier" text NOT NULL,
	"status" text NOT NULL,
	"current_period_end" timestamp,
	"founder_number" integer,
	"founder_purchased_at" timestamp,
	"cancel_at_period_end" boolean DEFAULT false NOT NULL,
	"token_balance" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"founding_supporter" boolean DEFAULT false NOT NULL,
	"granted_by" text,
	"subscribed_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp,
	CONSTRAINT "supporters_unique_0" UNIQUE("founder_number")
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"ticket_id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"user_id" text NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"completed_by" text,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "title_catalog" (
	"title_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "title_catalog_title_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"display" text NOT NULL,
	"source" text NOT NULL,
	"is_repeatable" boolean DEFAULT true NOT NULL,
	"how_to" text,
	"image_filename" text,
	CONSTRAINT "title_catalog_unique_0" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "topgg_vote_events" (
	"topgg_vote_id" text PRIMARY KEY NOT NULL,
	"event_type" text NOT NULL,
	"discord_id" text NOT NULL,
	"topgg_user_id" text,
	"voted_at" timestamp NOT NULL,
	"expires_at" timestamp,
	"weight" integer DEFAULT 1 NOT NULL,
	"daily_cycle" text NOT NULL,
	"delivery_trace" text,
	"outcome" text NOT NULL,
	"streak_number" integer,
	"random_reward" text,
	"milestone_reward" text,
	"rewarded_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_armors" (
	"discord_id" text NOT NULL,
	"armor_id" text PRIMARY KEY NOT NULL,
	"armor_roster_id" integer NOT NULL,
	"curr_hp" integer NOT NULL,
	"curr_def" integer NOT NULL,
	"enhancement" integer DEFAULT 1 NOT NULL,
	"base_hp" integer NOT NULL,
	"base_def" integer NOT NULL,
	"native_sockets" jsonb NOT NULL,
	"opposite_sockets" jsonb NOT NULL,
	"is_locked" boolean DEFAULT false NOT NULL,
	"obtained_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_character" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"class" text NOT NULL,
	"combat_level" integer DEFAULT 1 NOT NULL,
	"combat_exp" integer DEFAULT 0 NOT NULL,
	"active_preset_slot" integer DEFAULT 1 NOT NULL,
	"highest_raid_streak" integer DEFAULT 0 NOT NULL,
	"highest_rank_streak" integer DEFAULT 0 NOT NULL,
	"equipped_weapon_id" text,
	"active_deity_id" integer,
	"raids_won" integer DEFAULT 0 NOT NULL,
	"raids_lost" integer DEFAULT 0 NOT NULL,
	"pvp_wins" integer DEFAULT 0 NOT NULL,
	"pvp_losses" integer DEFAULT 0 NOT NULL,
	"believer_level" integer DEFAULT 1 NOT NULL,
	"believer_exp" integer DEFAULT 0 NOT NULL,
	"reputation_exp_today" integer DEFAULT 0 NOT NULL,
	"reputation_exp_reset_date" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"equipped_armor_id" text,
	"active_deity_id_2" integer,
	"active_deity_id_3" integer,
	"pvp_rating" integer DEFAULT 1000 NOT NULL,
	"boss_kills" integer DEFAULT 0 NOT NULL,
	"equipped_title_id" integer,
	"active_echo_deity_id" integer,
	"pvp_peak" integer DEFAULT 1000 NOT NULL,
	"last_weekly_claim_week" integer,
	"pvp_demotion_shield" boolean DEFAULT true NOT NULL,
	"boss_top_damage" integer DEFAULT 0 NOT NULL,
	"lifetime_exp" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_cosmetics" (
	"discord_id" text NOT NULL,
	"cosmetic_id" integer NOT NULL,
	"source" text NOT NULL,
	"acquired_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_cosmetics_discord_id_cosmetic_id_pk" PRIMARY KEY("discord_id","cosmetic_id")
);
--> statement-breakpoint
CREATE TABLE "user_deities" (
	"user_deity_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_deities_user_deity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"deity_id" integer NOT NULL,
	"curr_atk" integer NOT NULL,
	"curr_hp" integer NOT NULL,
	"curr_def" integer NOT NULL,
	"enhancement" integer DEFAULT 1 NOT NULL,
	"obtained_at" timestamp DEFAULT now() NOT NULL,
	"last_pull_date" text NOT NULL,
	"sigils" integer DEFAULT 0 NOT NULL,
	"ascended" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_deities_unique_0" UNIQUE("discord_id","deity_id")
);
--> statement-breakpoint
CREATE TABLE "user_guild_activity" (
	"discord_id" text NOT NULL,
	"guild_id" text NOT NULL,
	"last_active" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_guild_activity_discord_id_guild_id_pk" PRIMARY KEY("discord_id","guild_id")
);
--> statement-breakpoint
CREATE TABLE "user_presets" (
	"id" integer PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"slot" integer NOT NULL,
	"name" text,
	"equipped_deity_1_id" integer,
	"equipped_deity_2_id" integer,
	"equipped_deity_3_id" integer,
	"equipped_echo_deity_id" integer,
	"equipped_armor_id" text,
	"equipped_weapon_id" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_presets_unique_0" UNIQUE("discord_id","slot")
);
--> statement-breakpoint
CREATE TABLE "user_runes" (
	"rune_uid" text PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"rune_id" integer NOT NULL,
	"socketed_into" text,
	"is_locked" boolean DEFAULT false NOT NULL,
	"obtained_at" timestamp DEFAULT now() NOT NULL,
	"rolled_value" real
);
--> statement-breakpoint
CREATE TABLE "user_titles" (
	"discord_id" text NOT NULL,
	"title_id" integer NOT NULL,
	"earned_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_titles_discord_id_title_id_pk" PRIMARY KEY("discord_id","title_id")
);
--> statement-breakpoint
CREATE TABLE "user_weapons" (
	"discord_id" text NOT NULL,
	"weapon_id" text PRIMARY KEY NOT NULL,
	"weapon_roster_id" integer NOT NULL,
	"curr_atk" integer NOT NULL,
	"enhancement" integer DEFAULT 1 NOT NULL,
	"base_atk" integer NOT NULL,
	"crit" real NOT NULL,
	"bonus_dmg_pct" real,
	"is_locked" boolean DEFAULT false NOT NULL,
	"obtained_at" timestamp DEFAULT now() NOT NULL,
	"native_sockets" jsonb NOT NULL,
	"opposite_sockets" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"monthly_streak" integer DEFAULT 0 NOT NULL,
	"overall_streak" integer DEFAULT 0 NOT NULL,
	"last_daily_claim_date" text,
	"last_bestow_received" text,
	"bestow_received_today" integer DEFAULT 0 NOT NULL,
	"last_boss_attack_date" text,
	"is_banned" boolean DEFAULT false NOT NULL,
	"registered_at" timestamp DEFAULT now() NOT NULL,
	"quest_refreshes_today" integer DEFAULT 0 NOT NULL,
	"last_quest_refresh_date" text
);
--> statement-breakpoint
CREATE TABLE "users_bag" (
	"discord_id" text PRIMARY KEY NOT NULL,
	"credux" integer DEFAULT 0 NOT NULL,
	"belief_shards" integer DEFAULT 0 NOT NULL,
	"sacred_relics" integer DEFAULT 0 NOT NULL,
	"supreme_relics" integer DEFAULT 0 NOT NULL,
	"silver_chest" integer DEFAULT 0 NOT NULL,
	"gold_chest" integer DEFAULT 0 NOT NULL,
	"boss_treasure_chest" integer DEFAULT 0 NOT NULL,
	"boss_golden_chest" integer DEFAULT 0 NOT NULL,
	"supreme_chest" integer DEFAULT 0 NOT NULL,
	"epic_essence" integer DEFAULT 0 NOT NULL,
	"mythic_essence" integer DEFAULT 0 NOT NULL,
	"legendary_essence" integer DEFAULT 0 NOT NULL,
	"supreme_essence" integer DEFAULT 0 NOT NULL,
	"lifetime_credux_earned" integer DEFAULT 0 NOT NULL,
	"lesser_rune_bag" integer DEFAULT 0 NOT NULL,
	"greater_rune_bag" integer DEFAULT 0 NOT NULL,
	"divine_rune_bag" integer DEFAULT 0 NOT NULL,
	"valor_medals" integer DEFAULT 0 NOT NULL,
	"custom_avatar_token" integer DEFAULT 0 NOT NULL,
	"custom_deity_token" integer DEFAULT 0 NOT NULL,
	"change_class" integer DEFAULT 0 NOT NULL,
	"diamond_chest" integer DEFAULT 0 NOT NULL,
	"genesis_chest" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wager_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wager_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"challenger_id" text NOT NULL,
	"opponent_id" text NOT NULL,
	"winner_id" text NOT NULL,
	"amount" integer NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weapon_roster" (
	"weapon_roster_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "weapon_roster_weapon_roster_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"type" text NOT NULL,
	"tier" text NOT NULL,
	"mythology" text NOT NULL,
	"passive_key" text NOT NULL,
	"passive_name" text NOT NULL,
	"passive_description" text NOT NULL,
	"lore" text,
	"image_filename" text,
	"is_available" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weekly_grand" (
	"discord_id" text NOT NULL,
	"quest_week" integer NOT NULL,
	"claimed" boolean DEFAULT false NOT NULL,
	CONSTRAINT "weekly_grand_discord_id_quest_week_pk" PRIMARY KEY("discord_id","quest_week")
);
--> statement-breakpoint
CREATE TABLE "weekly_quests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "weekly_quests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"discord_id" text NOT NULL,
	"quest_type" text NOT NULL,
	"target_count" integer NOT NULL,
	"current_count" integer DEFAULT 0 NOT NULL,
	"reward_credux" integer NOT NULL,
	"reward_valor" integer NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"quest_week" integer NOT NULL,
	CONSTRAINT "weekly_quests_unique_0" UNIQUE("discord_id","quest_type","quest_week")
);
--> statement-breakpoint
ALTER TABLE "active_battles" ADD CONSTRAINT "active_battles_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "active_battles" ADD CONSTRAINT "active_battles_mob_id_mob_roster_mob_id_fk" FOREIGN KEY ("mob_id") REFERENCES "public"."mob_roster"("mob_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "active_casino_sessions" ADD CONSTRAINT "active_casino_sessions_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "active_duel_participants" ADD CONSTRAINT "active_duel_participants_duel_id_active_duels_duel_id_fk" FOREIGN KEY ("duel_id") REFERENCES "public"."active_duels"("duel_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boss_attack_log" ADD CONSTRAINT "boss_attack_log_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boss_state" ADD CONSTRAINT "boss_state_mob_id_mob_roster_mob_id_fk" FOREIGN KEY ("mob_id") REFERENCES "public"."mob_roster"("mob_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_quest_completion_rewards" ADD CONSTRAINT "daily_quest_completion_rewards_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_quests" ADD CONSTRAINT "daily_quests_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "equipped_skins" ADD CONSTRAINT "equipped_skins_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "equipped_skins" ADD CONSTRAINT "equipped_skins_cosmetic_id_cosmetic_catalog_cosmetic_id_fk" FOREIGN KEY ("cosmetic_id") REFERENCES "public"."cosmetic_catalog"("cosmetic_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pity_counters" ADD CONSTRAINT "pity_counters_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pvp_shop_purchases" ADD CONSTRAINT "pvp_shop_purchases_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raid_reward_daily_totals" ADD CONSTRAINT "raid_reward_daily_totals_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raid_reward_grants" ADD CONSTRAINT "raid_reward_grants_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ranked_logs" ADD CONSTRAINT "ranked_logs_player_id_users_discord_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seasons" ADD CONSTRAINT "seasons_featured_deity_id_deity_roster_deity_id_fk" FOREIGN KEY ("featured_deity_id") REFERENCES "public"."deity_roster"("deity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "summon_reward_grants" ADD CONSTRAINT "summon_reward_grants_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supporter_item_grants" ADD CONSTRAINT "supporter_item_grants_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supporter_token_ledger" ADD CONSTRAINT "supporter_token_ledger_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supporters" ADD CONSTRAINT "supporters_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_user_id_users_discord_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_armors" ADD CONSTRAINT "user_armors_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_armors" ADD CONSTRAINT "user_armors_armor_roster_id_armor_roster_armor_roster_id_fk" FOREIGN KEY ("armor_roster_id") REFERENCES "public"."armor_roster"("armor_roster_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_equipped_weapon_id_user_weapons_weapon_id_fk" FOREIGN KEY ("equipped_weapon_id") REFERENCES "public"."user_weapons"("weapon_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_active_deity_id_user_deities_user_deity_id_fk" FOREIGN KEY ("active_deity_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_equipped_armor_id_user_armors_armor_id_fk" FOREIGN KEY ("equipped_armor_id") REFERENCES "public"."user_armors"("armor_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_active_deity_id_2_user_deities_user_deity_id_fk" FOREIGN KEY ("active_deity_id_2") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_active_deity_id_3_user_deities_user_deity_id_fk" FOREIGN KEY ("active_deity_id_3") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_equipped_title_id_title_catalog_title_id_fk" FOREIGN KEY ("equipped_title_id") REFERENCES "public"."title_catalog"("title_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "user_character_active_echo_deity_id_user_deities_user_deity_id_fk" FOREIGN KEY ("active_echo_deity_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_cosmetics" ADD CONSTRAINT "user_cosmetics_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_cosmetics" ADD CONSTRAINT "user_cosmetics_cosmetic_id_cosmetic_catalog_cosmetic_id_fk" FOREIGN KEY ("cosmetic_id") REFERENCES "public"."cosmetic_catalog"("cosmetic_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_deities" ADD CONSTRAINT "user_deities_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_deities" ADD CONSTRAINT "user_deities_deity_id_deity_roster_deity_id_fk" FOREIGN KEY ("deity_id") REFERENCES "public"."deity_roster"("deity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_guild_activity" ADD CONSTRAINT "user_guild_activity_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_deity_1_id_user_deities_user_deity_id_fk" FOREIGN KEY ("equipped_deity_1_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_deity_2_id_user_deities_user_deity_id_fk" FOREIGN KEY ("equipped_deity_2_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_deity_3_id_user_deities_user_deity_id_fk" FOREIGN KEY ("equipped_deity_3_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_echo_deity_id_user_deities_user_deity_id_fk" FOREIGN KEY ("equipped_echo_deity_id") REFERENCES "public"."user_deities"("user_deity_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_armor_id_user_armors_armor_id_fk" FOREIGN KEY ("equipped_armor_id") REFERENCES "public"."user_armors"("armor_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_equipped_weapon_id_user_weapons_weapon_id_fk" FOREIGN KEY ("equipped_weapon_id") REFERENCES "public"."user_weapons"("weapon_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_runes" ADD CONSTRAINT "user_runes_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_runes" ADD CONSTRAINT "user_runes_rune_id_rune_roster_rune_id_fk" FOREIGN KEY ("rune_id") REFERENCES "public"."rune_roster"("rune_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_titles" ADD CONSTRAINT "user_titles_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_titles" ADD CONSTRAINT "user_titles_title_id_title_catalog_title_id_fk" FOREIGN KEY ("title_id") REFERENCES "public"."title_catalog"("title_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_weapons" ADD CONSTRAINT "user_weapons_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_weapons" ADD CONSTRAINT "user_weapons_weapon_roster_id_weapon_roster_weapon_roster_id_fk" FOREIGN KEY ("weapon_roster_id") REFERENCES "public"."weapon_roster"("weapon_roster_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users_bag" ADD CONSTRAINT "users_bag_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weekly_grand" ADD CONSTRAINT "weekly_grand_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "weekly_quests" ADD CONSTRAINT "weekly_quests_discord_id_users_discord_id_fk" FOREIGN KEY ("discord_id") REFERENCES "public"."users"("discord_id") ON DELETE no action ON UPDATE no action;