-- Stop the application during this migration; deploy at a weekly boundary.
-- Ambiguous week-only history is preserved under legacy-W keys; do not guess its year.
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM user_character c LEFT JOIN user_presets p ON p.discord_id = c.discord_id AND p.slot = c.active_preset_slot WHERE p.id IS NULL) THEN
  RAISE EXCEPTION 'Missing active preset: reconcile loadouts before migration';
 END IF;
 IF (SELECT count(*) FROM seasons WHERE is_active) > 1 THEN
  RAISE EXCEPTION 'Multiple active seasons: reconcile shop purchases before migration';
 END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_equipped_weapon_id_user_weapons_weapon_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_active_deity_id_user_deities_user_deity_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_equipped_armor_id_user_armors_armor_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_active_deity_id_2_user_deities_user_deity_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_active_deity_id_3_user_deities_user_deity_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" DROP CONSTRAINT "user_character_active_echo_deity_id_user_deities_user_deity_id_fk";
--> statement-breakpoint
ALTER TABLE "user_character" ALTER COLUMN "last_weekly_claim_week" TYPE text USING CASE WHEN last_weekly_claim_week IS NULL THEN NULL ELSE 'legacy-W' || last_weekly_claim_week::text END;--> statement-breakpoint
ALTER TABLE "user_presets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "user_presets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "weekly_grand" ALTER COLUMN "quest_week" TYPE text USING 'legacy-W' || quest_week::text;--> statement-breakpoint
ALTER TABLE "weekly_quests" ALTER COLUMN "quest_week" TYPE text USING 'legacy-W' || quest_week::text;--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('user_presets', 'id'), COALESCE((SELECT MAX(id) + 1 FROM user_presets), 1), false);
--> statement-breakpoint
CREATE UNIQUE INDEX "seasons_one_active" ON "seasons" USING btree ("is_active") WHERE "seasons"."is_active" = true;--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "equipped_weapon_id";--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "active_deity_id";--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "equipped_armor_id";--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "active_deity_id_2";--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "active_deity_id_3";--> statement-breakpoint
ALTER TABLE "user_character" DROP COLUMN "active_echo_deity_id";--> statement-breakpoint
ALTER TABLE "seasons" ADD CONSTRAINT "seasons_valid_window" CHECK ("seasons"."ends_at" > "seasons"."starts_at");--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "character_valid_class" CHECK ("user_character"."class" IN ('Swordsman', 'Fighter', 'Mage', 'Knight', 'Archer'));--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "character_valid_preset" CHECK ("user_character"."active_preset_slot" IN (1, 2));--> statement-breakpoint
ALTER TABLE "user_character" ADD CONSTRAINT "character_valid_level" CHECK ("user_character"."combat_level" BETWEEN 1 AND 50);--> statement-breakpoint
ALTER TABLE "user_presets" ADD CONSTRAINT "user_presets_valid_slot" CHECK ("user_presets"."slot" IN (1, 2));--> statement-breakpoint
ALTER TABLE "users_bag" ADD CONSTRAINT "bag_nonnegative_currency" CHECK ("users_bag"."credux" >= 0 AND "users_bag"."belief_shards" >= 0 AND "users_bag"."valor_medals" >= 0);
--> statement-breakpoint
ALTER TABLE user_weapons ADD CONSTRAINT user_weapons_valid_enhancement CHECK (enhancement BETWEEN 1 AND 21);
--> statement-breakpoint
ALTER TABLE user_armors ADD CONSTRAINT user_armors_valid_enhancement CHECK (enhancement BETWEEN 1 AND 21);
