import { MOBS_TEXT } from '../../../shared/ui/text/catalog/mobs.js';
/**
 * SEED DATA — mob_roster
 * ---------------------------------------------------------------------------
 * Text hiển thị: src/shared/ui/text/catalog/mobs.ts; chạy pnpm db:seed sau khi sửa.
 *
 * mobType : 'regular' (mob thường trong /raid) | 'elite' | 'boss'
 *           — RaidService hiện chỉ roll mobType='regular'.
 * hpPerLevel / atkPerLevel / defPerLevel: cộng dồn mỗi cấp của người chơi
 *           (stat = base + perLevel * (level - 1)).
 * immunityTags / specialFlags: mảng JSON (hiện engine M3 chưa đọc, để sẵn).
 */

export interface MobSeed {
	mobId: number;
	name: string;
	mythology: string;
	mobType: 'regular' | 'elite' | 'boss';
	baseHp: number;
	baseAtk: number;
	baseDef: number;
	baseCrit: number;
	hpPerLevel: number;
	atkPerLevel: number;
	defPerLevel: number;
	skillKey: string;
	skillName: string;
	skillDescription: string;
	immunityTags: string[];
	specialFlags: string[];
}

export const MOB_SEED: MobSeed[] = [
	// ── Regular ──────────────────────────────────────────────────────────────
	{
		mobId: 1,
		name: MOBS_TEXT['1'].name,
		mythology: MOBS_TEXT['1'].mythology,
		mobType: 'regular',
		baseHp: 550,
		baseAtk: 120,
		baseDef: 60,
		baseCrit: 3.0,
		hpPerLevel: 45,
		atkPerLevel: 10,
		defPerLevel: 5,
		skillKey: 'blood_moon_leap',
		skillName: MOBS_TEXT['1'].skillName,
		skillDescription: MOBS_TEXT['1'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 2,
		name: MOBS_TEXT['2'].name,
		mythology: MOBS_TEXT['2'].mythology,
		mobType: 'regular',
		baseHp: 480,
		baseAtk: 105,
		baseDef: 45,
		baseCrit: 5.0,
		hpPerLevel: 40,
		atkPerLevel: 9,
		defPerLevel: 4,
		skillKey: 'wing_clippers',
		skillName: MOBS_TEXT['2'].skillName,
		skillDescription: MOBS_TEXT['2'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 3,
		name: MOBS_TEXT['3'].name,
		mythology: MOBS_TEXT['3'].mythology,
		mobType: 'regular',
		baseHp: 700,
		baseAtk: 135,
		baseDef: 80,
		baseCrit: 2.0,
		hpPerLevel: 55,
		atkPerLevel: 11,
		defPerLevel: 6,
		skillKey: 'trail_haze',
		skillName: MOBS_TEXT['3'].skillName,
		skillDescription: MOBS_TEXT['3'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 4,
		name: MOBS_TEXT['4'].name,
		mythology: MOBS_TEXT['4'].mythology,
		mobType: 'regular',
		baseHp: 820,
		baseAtk: 110,
		baseDef: 95,
		baseCrit: 1.0,
		hpPerLevel: 65,
		atkPerLevel: 9,
		defPerLevel: 7,
		skillKey: 'cigar_smoke',
		skillName: MOBS_TEXT['4'].skillName,
		skillDescription: MOBS_TEXT['4'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},

	// ── Elite (loot branch chưa port — chỉ seed sẵn) ─────────────────────────
	{
		mobId: 101,
		name: MOBS_TEXT['101'].name,
		mythology: MOBS_TEXT['101'].mythology,
		mobType: 'elite',
		baseHp: 1500,
		baseAtk: 220,
		baseDef: 130,
		baseCrit: 6.0,
		hpPerLevel: 90,
		atkPerLevel: 16,
		defPerLevel: 9,
		skillKey: 'flesh_feast',
		skillName: MOBS_TEXT['101'].skillName,
		skillDescription: MOBS_TEXT['101'].skillDescription,
		immunityTags: ['poison'],
		specialFlags: ['lifesteal'],
	},

	// ── Boss (mechanics riêng chưa port — seed sẵn) ──────────────────────────
	{
		mobId: 201,
		name: MOBS_TEXT['201'].name,
		mythology: MOBS_TEXT['201'].mythology,
		mobType: 'boss',
		baseHp: 4000,
		baseAtk: 350,
		baseDef: 220,
		baseCrit: 4.0,
		hpPerLevel: 180,
		atkPerLevel: 25,
		defPerLevel: 14,
		skillKey: 'moon_threshold',
		skillName: MOBS_TEXT['201'].skillName,
		skillDescription: MOBS_TEXT['201'].skillDescription,
		immunityTags: ['stun'],
		specialFlags: ['phase_two'],
	},

	{
		mobId: 5,
		name: MOBS_TEXT['5'].name,
		mythology: MOBS_TEXT['5'].mythology,
		mobType: 'regular',
		baseHp: 520,
		baseAtk: 125,
		baseDef: 50,
		baseCrit: 4.0,
		hpPerLevel: 42,
		atkPerLevel: 10,
		defPerLevel: 4,
		skillKey: 'venom_spit',
		skillName: MOBS_TEXT['5'].skillName,
		skillDescription: MOBS_TEXT['5'].skillDescription,
		immunityTags: ['venom'],
		specialFlags: [],
	},
	{
		mobId: 6,
		name: MOBS_TEXT['6'].name,
		mythology: MOBS_TEXT['6'].mythology,
		mobType: 'regular',
		baseHp: 460,
		baseAtk: 115,
		baseDef: 45,
		baseCrit: 6.0,
		hpPerLevel: 38,
		atkPerLevel: 9,
		defPerLevel: 4,
		skillKey: 'blood_frenzy',
		skillName: MOBS_TEXT['6'].skillName,
		skillDescription: MOBS_TEXT['6'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 7,
		name: MOBS_TEXT['7'].name,
		mythology: MOBS_TEXT['7'].mythology,
		mobType: 'regular',
		baseHp: 500,
		baseAtk: 120,
		baseDef: 55,
		baseCrit: 5.0,
		hpPerLevel: 40,
		atkPerLevel: 10,
		defPerLevel: 5,
		skillKey: 'wing_clippers',
		skillName: MOBS_TEXT['7'].skillName,
		skillDescription: MOBS_TEXT['7'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 8,
		name: MOBS_TEXT['8'].name,
		mythology: MOBS_TEXT['8'].mythology,
		mobType: 'regular',
		baseHp: 780,
		baseAtk: 105,
		baseDef: 90,
		baseCrit: 1.0,
		hpPerLevel: 62,
		atkPerLevel: 9,
		defPerLevel: 7,
		skillKey: 'stone_hide',
		skillName: MOBS_TEXT['8'].skillName,
		skillDescription: MOBS_TEXT['8'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 9,
		name: MOBS_TEXT['9'].name,
		mythology: MOBS_TEXT['9'].mythology,
		mobType: 'regular',
		baseHp: 560,
		baseAtk: 130,
		baseDef: 60,
		baseCrit: 3.0,
		hpPerLevel: 44,
		atkPerLevel: 11,
		defPerLevel: 5,
		skillKey: 'blood_frenzy',
		skillName: MOBS_TEXT['9'].skillName,
		skillDescription: MOBS_TEXT['9'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
	{
		mobId: 10,
		name: MOBS_TEXT['10'].name,
		mythology: MOBS_TEXT['10'].mythology,
		mobType: 'regular',
		baseHp: 600,
		baseAtk: 110,
		baseDef: 70,
		baseCrit: 2.0,
		hpPerLevel: 46,
		atkPerLevel: 9,
		defPerLevel: 6,
		skillKey: 'cigar_smoke',
		skillName: MOBS_TEXT['10'].skillName,
		skillDescription: MOBS_TEXT['10'].skillDescription,
		immunityTags: ['burn'],
		specialFlags: [],
	},

	// ── Elite mới ────────────────────────────────────────────────────────────
	{
		mobId: 102,
		name: MOBS_TEXT['102'].name,
		mythology: MOBS_TEXT['102'].mythology,
		mobType: 'elite',
		baseHp: 1350,
		baseAtk: 245,
		baseDef: 110,
		baseCrit: 7.0,
		hpPerLevel: 85,
		atkPerLevel: 17,
		defPerLevel: 8,
		skillKey: 'blood_frenzy',
		skillName: MOBS_TEXT['102'].skillName,
		skillDescription: MOBS_TEXT['102'].skillDescription,
		immunityTags: ['venom'],
		specialFlags: [],
	},
	{
		mobId: 103,
		name: MOBS_TEXT['103'].name,
		mythology: MOBS_TEXT['103'].mythology,
		mobType: 'elite',
		baseHp: 1700,
		baseAtk: 200,
		baseDef: 160,
		baseCrit: 2.0,
		hpPerLevel: 95,
		atkPerLevel: 15,
		defPerLevel: 11,
		skillKey: 'stone_hide',
		skillName: MOBS_TEXT['103'].skillName,
		skillDescription: MOBS_TEXT['103'].skillDescription,
		immunityTags: ['poison', 'venom'],
		specialFlags: [],
	},
	{
		mobId: 104,
		name: MOBS_TEXT['104'].name,
		mythology: MOBS_TEXT['104'].mythology,
		mobType: 'elite',
		baseHp: 1500,
		baseAtk: 230,
		baseDef: 130,
		baseCrit: 5.0,
		hpPerLevel: 90,
		atkPerLevel: 16,
		defPerLevel: 9,
		skillKey: 'venom_spit',
		skillName: MOBS_TEXT['104'].skillName,
		skillDescription: MOBS_TEXT['104'].skillDescription,
		immunityTags: [],
		specialFlags: [],
	},
];
